spring.application.name=GEVORGYAN'S Salon

# --- Web
server.port=8080
spring.thymeleaf.cache=false

# --- DB (PostgreSQL)
# Start DB: docker compose up -d
spring.datasource.url=jdbc:postgresql://localhost:5432/salon
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# --- i18n
spring.messages.basename=messages
spring.messages.encoding=UTF-8

# --- Admin credentials (change in production)
app.admin.username=admin
app.admin.password=admin123

# --- Business hours (default availability)
app.hours.open=10:00
app.hours.close=20:00

# --- Mail (Gmail SMTP)
# IMPORTANT:
# - Turn on 2-Step Verification in your Google account
# - Create an App Password and use it as SMTP password (NOT your normal Gmail password)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gevorgyanarman525@gmail.com
spring.mail.password=ggnxnldjsjuoejlp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.debug=true
logging.level.org.springframework.mail=DEBUG

app.mail.from="gevorgyanarman525@gmail.com"

